# Generated by Django 5.0.3 on 2024-04-22 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musycal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='musycal.album'),
        ),
    ]
