# Generated by Django 5.0.3 on 2024-04-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musycal', '0003_alter_song_album'),
        ('musycal', '0003_genre_alter_song_album_song_genre'),
    ]

    operations = [
    ]
