# Generated by Django 5.0.3 on 2024-04-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_artist_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
