# Generated by Django 5.0.3 on 2024-04-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_artist_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='dob',
            field=models.DateField(default='2024-04-25'),
        ),
        migrations.AddField(
            model_name='artist',
            name='lakab',
            field=models.CharField(default='Bakshi', max_length=10),
        ),
    ]
