# Generated by Django 5.0.3 on 2024-05-02 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_artist_dob_artist_lakab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='album',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.album'),
        ),
    ]
