# Generated by Django 5.0.3 on 2024-05-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instrument_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='songs',
            name='instruments',
            field=models.ManyToManyField(to='app.instruments'),
        ),
    ]
